name: Metrics
on:
  # Agenda a atualização a cada 12 horas
  schedule: [{cron: "0 */12 * * *"}]
  # Permite que você execute manualmente para testar
  workflow_dispatch:
  # Atualiza sempre que você fizer um push no README
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Aqui ele usa o "Secret" que você criou
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Configurações do gráfico
          user: IvanGSilva
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Ativa a contagem de commits privados
          config_timezone: America/Sao_Paulo
          commits_authoring: IvanGSilva, ivangsilva@seu-email-da-empresa.com
